version: '3.8'

services:
  adminer:
    container_name: adminer
    hostname: adminer
    build:
      context: .
      dockerfile: ./services/adminer/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - main

networks:
  main:
    external:
      name: data_net