version: '3.8'

services:
  adminer:
    container_name: adminer
    hostname: adminer
    build:
      context: .
      dockerfile: ./services/adminer/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - main

  db:
    container_name: db
    hostname: db
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - main

networks:
  main:
    name: main
    driver: bridge