version: '3.8'

services:
  adminer:
    container_name: adminer
    hostname: adminer
    build:
      context: .
      dockerfile: ./services/adminer/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - data

  db:
    container_name: db
    hostname: db
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - data

networks:
  data:
    driver: bridge
    name: data_net