version: '3.8'

services:
  db:
    container_name: db
    hostname: db
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    networks:
      - data

networks:
  data:
    driver: bridge
    name: data_net